Implement the push subcommand

diff --git a/bin/git-chord b/bin/git-chord
--- a/bin/git-chord
+++ b/bin/git-chord
@@ -23,7 +23,7 @@ OPTIONS="$( printf '%s' '
 trackers.prefix chord/ # Sets the tracker branch prefix
 trackers.name main # Sets the tracker branch name
 trackers.remotes.default origin # Sets the default remote name for tracker branches
-trackers.remotes.allowautoadd true # Allows automatically adding the default remote if necessary
+trackers.remotes.allowautoassociate true # Allows automatically associate the default remote if necessary
 branches.store.enabled true # Enables saving state of tracked branches
 branches.store.regex .* # Sets the regex pattern for saving tracked branches
 branches.apply.enabled true # Enables applying the saved state of tracked branches
@@ -556,6 +556,24 @@ escapeMarkdown() ( # stdin
     done
 )
 
+printLogMessage() { # $1: message
+    if checkTruthy "$configValue_markdown"; then
+        printf -- '- %s\n' "$1"
+    else
+        printf '%s\n' "$1"
+    fi
+}
+
+logInfoMessage() { # $1: message
+    if checkTruthy "$configValue_verbose"; then
+        printLogMessage "${formatInfo}INFO: ${1}${formatInfoEnd}"
+    fi
+}
+
+logWarningMessage() { # $1: message
+    printLogMessage "${formatWarning}WARNING: ${1}${formatWarningEnd}"
+}
+
 printGrandTitle() { # $1: title
     if checkTruthy "$configValue_markdown"; then
         printf '# %s\n\n' "$1" | applyInlineFormatting | escapeMarkdown
@@ -972,24 +990,6 @@ printTreeVerboseDiff() ( # $1: stateYaml1, $2: stateYaml2, $3: keyPrefix, $4: se
         printf '%s' "$messageLines" | printListStdin
     fi
 )
-
-printLogMessage() { # $1: message
-    if checkTruthy "$configValue_markdown"; then
-        printf -- '- %s\n' "$1"
-    else
-        printf '%s\n' "$1"
-    fi
-}
-
-logInfoMessage() { # $1: message
-    if checkTruthy "$configValue_verbose"; then
-        printLogMessage "${formatInfo}INFO: ${1}${formatInfoEnd}"
-    fi
-}
-
-logWarningMessage() { # $1: message
-    printLogMessage "${formatWarning}WARNING: ${1}${formatWarningEnd}"
-}
 
 if [ "$subcommand" = 'help' ] || [ "$subcommand" = '-h' ]; then
     case "$command" in
@@ -1951,8 +1951,48 @@ EOF
         exit 0
         ;;
     push)
-        printf '%sERROR: %s%s\n' "$formatError" 'The push command is not implemented yet' "$formatErrorEnd" >&2
-        exit 1
+        trackerBranches=''
+        if checkTruthy "$configValue_all"; then
+            trackerBranches="$( git for-each-ref --format='%(refname:short)' refs/heads | awk --assign search='chord/' 'substr($0, 1, length(search)) == search { print }' )"
+        else
+            defaultTrackerBranch="${configValue_trackers_prefix}${configValue_trackers_name}"
+            if ! git show-ref --verify --quiet "refs/heads/${defaultTrackerBranch}"; then
+                printf '%sERROR: %s %s%s\n' "$formatError" "Default tracker branch doesn't exist:" "$defaultTrackerBranch" "$formatErrorEnd" >&2
+                exit 1
+            fi
+            trackerBranches="$( appendLine "$trackerBranches" "$defaultTrackerBranch" )"
+        fi
+        printf '%s\n' "$trackerBranches" | while IFS= read -r trackerBranch; do
+            logInfoMessage "Push tracker branch: ${trackerBranch}"
+            remoteName="$( git config "branch.${trackerBranch}.remote" )"
+            remoteBranch="$( git for-each-ref --format='%(upstream:short)' "refs/heads/${trackerBranch}" )"
+            if [ -z "$remoteBranch" ]; then
+                logInfoMessage "No remote is set for ${trackerBranch}, setup..."
+                if [ -z "$configValue_trackers_remotes_default" ]; then
+                    logWarningMessage 'No default remote is set'
+                    continue
+                elif ! git remote get-url "$configValue_trackers_remotes_default" > /dev/null 2>/dev/null; then
+                    logWarningMessage "The default remote doesn't exist: ${configValue_trackers_remotes_default}"
+                    continue
+                fi
+                remoteName="$configValue_trackers_remotes_default"
+                remoteBranch="$trackerBranch"
+                if ! checkTruthy "$configValue_dryrun"; then
+                    if ! git branch --set-upstream-to="${configValue_trackers_remotes_default}/${remoteBranch}" "$trackerBranch"; then
+                        logWarningMessage "Failed to setup remote for ${trackerBranch}"
+                        continue
+                    fi
+                fi
+            fi 
+            logInfoMessage "Push tracker branch ${trackerBranch} to ${trackerBranch}:${remoteBranch}"
+            if ! checkTruthy "$configValue_dryrun"; then
+                if ! git push "$remoteName" "${trackerBranch}:${remoteBranch}"; then
+                    logWarningMessage "Failed to push tracker branch ${trackerBranch} to ${trackerBranch}:${remoteBranch}"
+                    continue
+                fi
+            fi
+        done
+        exit 0
         ;;
     pull)
         printf '%sERROR: %s%s\n' "$formatError" 'The pull command is not implemented yet' "$formatErrorEnd" >&2
