Fix format ends

diff --git a/bin/git-chord b/bin/git-chord
--- a/bin/git-chord
+++ b/bin/git-chord
@@ -505,23 +505,26 @@ getWorkingtreeTreeId() ( # subshell local: $gitDir, $tmpGitDir, $$treeId, $linki
     linkingSupported=''
     
     if [ -e "${tmpGitDir}" ] || [ -e "${gitDir}/objects/${testFileName}" ]; then
-        printf '%sERROR: %s%s\n' "$formatError" 'Temporary git chord entries detected on the file system. Abort.' "$formatBoldEnd" >&2
+        printf '%sERROR: %s%s\n' "$formatError" 'Temporary git chord entries detected on the file system. Abort.' "$formatErrorEnd" >&2
         exit 1
     fi
 
     GIT_DIR="$tmpGitDir" git init -q && rm -rf "${tmpGitDir}/objects" || {
-        printf '%sERROR: %s%s\n' "$formatError" 'Failed to prepare the temporary git directory. Abort.' "$formatBoldEnd" >&2
+        printf '%sERROR: %s%s\n' "$formatError" 'Failed to prepare the temporary git directory. Abort.' "$formatErrorEnd" >&2
         exit 1
     }
     
     touch "${gitDir}/objects/${testFileName}"
-    ln -s "$( realpath "${gitDir}/objects" )" "${tmpGitDir}/objects"
+    #ln -s "$( realpath "${gitDir}/objects" )" "${tmpGitDir}/objects"
     if [ -f "${tmpGitDir}/objects/${testFileName}" ]; then
         linkingSupported='1'
     else
+        if checkTruthy "$configValue_verbose"; then
+            printf '%sWARNING: %s%s\n' "$formatWarning" 'Failed to link to the git objects directory. Trying copy.' "$formatWarningEnd" >&2
+        fi
         mv "${gitDir}/objects" "${tmpGitDir}/objects"
         if ! [ -f "${tmpGitDir}/objects/${testFileName}" ]; then
-            printf '%sERROR: %s%s\n' "$formatError" 'Failed to link or move the git objects directory. Abort.' "$formatBoldEnd" >&2
+            printf '%sERROR: %s%s\n' "$formatError" 'Failed to link or move the git objects directory. Abort.' "$formatErrorEnd" >&2
             exit 1
         fi
     fi
@@ -530,14 +533,14 @@ getWorkingtreeTreeId() ( # subshell local: $gitDir, $tmpGitDir, $$treeId, $linki
     treeId="$( GIT_DIR="$tmpGitDir" git write-tree )"
 
     if [ -z "$treeId" ]; then
-        printf '%sERROR: %s%s\n' "$formatError" 'Failed to calculate the tree id of the working tree. Abort.' "$formatBoldEnd" >&2
+        printf '%sERROR: %s%s\n' "$formatError" 'Failed to calculate the tree id of the working tree. Abort.' "$formatErrorEnd" >&2
         exit 1
     fi
     
     if [ -z "$linkingSupported" ]; then
         mv "${tmpGitDir}/objects" "${gitDir}/objects"
         if ! [ -f "${gitDir}/objects/${testFileName}" ]; then
-            printf '%sERROR: %s%s\n' "$formatError" 'Failed to move the git objects directory back to the original location. Abort.' "$formatBoldEnd" >&2
+            printf '%sERROR: %s%s\n' "$formatError" 'Failed to move the git objects directory back to the original location. Abort.' "$formatErrorEnd" >&2
             exit 1
         fi
     fi
@@ -696,7 +699,7 @@ if [ "$subcommand" = 'help' ] || [ "$subcommand" = '-h' ]; then
         # TODO: push
         # TODO: pull
         *)
-            printf '%sERROR: %s: %s%s\n' "$formatError" 'No help for subcommand' "$subcommand" "$formatBoldEnd" >&2
+            printf '%sERROR: %s: %s%s\n' "$formatError" 'No help for subcommand' "$subcommand" "$formatErrorEnd" >&2
             exit 1
             ;;
     esac
@@ -791,7 +794,7 @@ case "$command" in
                 fi
                 exit 0
             elif [ "$subcommand" = 'set' ]; then
-                printf '%sERROR: %s%s\n' "$formatError" 'Default value can not be changed' "$formatBoldEnd" >&2
+                printf '%sERROR: %s%s\n' "$formatError" 'Default value can not be changed' "$formatErrorEnd" >&2
                 exit 1
             fi
         fi
@@ -799,7 +802,7 @@ case "$command" in
 esac
 
 if ! git rev-parse --git-dir > /dev/null 2>&1; then
-    printf '%sERROR: %s%s\n' "$formatError" 'Not a git repository' "$formatBoldEnd" >&2
+    printf '%sERROR: %s%s\n' "$formatError" 'Not a git repository' "$formatErrorEnd" >&2
     exit 1
 fi
 
@@ -856,21 +859,21 @@ case "$command" in
                 exit 2
             fi
             if ! git config "chord.${configKey}" "$configNewValue"; then
-                printf '%sERROR: %s%s\n' "$formatError" 'Failed to set value' "$formatBoldEnd" >&2
+                printf '%sERROR: %s%s\n' "$formatError" 'Failed to set value' "$formatErrorEnd" >&2
                 exit 1
             fi
         else
-            printf '%sERROR: %s: %s%s\n' "$formatError" 'Unknown subcommand of config' "$subcommand" "$formatBoldEnd" >&2
+            printf '%sERROR: %s: %s%s\n' "$formatError" 'Unknown subcommand of config' "$subcommand" "$formatErrorEnd" >&2
             exit 1
         fi
         exit 0
         ;;
     snapshot)
-        printf '%sERROR: %s%s\n' "$formatError" 'The snapshot command is not implemented yet' "$formatBoldEnd" >&2
+        printf '%sERROR: %s%s\n' "$formatError" 'The snapshot command is not implemented yet' "$formatErrorEnd" >&2
         exit 1
         ;;
     apply)
-        printf '%sERROR: %s%s\n' "$formatError" 'The apply command is not implemented yet' "$formatBoldEnd" >&2
+        printf '%sERROR: %s%s\n' "$formatError" 'The apply command is not implemented yet' "$formatErrorEnd" >&2
         exit 1
         ;;
     state)
@@ -878,23 +881,23 @@ case "$command" in
         exit 0
         ;;
     show)
-        printf '%sERROR: %s%s\n' "$formatError" 'The show command is not implemented yet' "$formatBoldEnd" >&2
+        printf '%sERROR: %s%s\n' "$formatError" 'The show command is not implemented yet' "$formatErrorEnd" >&2
         exit 1
         ;;
     diff)
-        printf '%sERROR: %s%s\n' "$formatError" 'The diff command is not implemented yet' "$formatBoldEnd" >&2
+        printf '%sERROR: %s%s\n' "$formatError" 'The diff command is not implemented yet' "$formatErrorEnd" >&2
         exit 1
         ;;
     push)
-        printf '%sERROR: %s%s\n' "$formatError" 'The push command is not implemented yet' "$formatBoldEnd" >&2
+        printf '%sERROR: %s%s\n' "$formatError" 'The push command is not implemented yet' "$formatErrorEnd" >&2
         exit 1
         ;;
     pull)
-        printf '%sERROR: %s%s\n' "$formatError" 'The pull command is not implemented yet' "$formatBoldEnd" >&2
+        printf '%sERROR: %s%s\n' "$formatError" 'The pull command is not implemented yet' "$formatErrorEnd" >&2
         exit 1
         ;;
     *)
-        printf '%sERROR: %s%s\n' "$formatError" 'Unknown command' "$formatBoldEnd" >&2
+        printf '%sERROR: %s%s\n' "$formatError" 'Unknown command' "$formatErrorEnd" >&2
         exit 1
         ;;
 esac
