Add a sketchy implementation of the list command

diff --git a/bin/git-chord b/bin/git-chord
--- a/bin/git-chord
+++ b/bin/git-chord
@@ -11,6 +11,7 @@ snapshot # Creates a snapshot of the repository state
 apply # Applies a previously saved snapshot to the repository
 state # Shows the current state based on the configuration
 show # Shows full data of a previously saved snapshot
+list # Lists previously saved snapshots
 diff # Shows diff between a previously saved snapshot and the current state
 delete # Deletes a previously saved snapshot
 push # Pushes the default chord branch (or using (`--all`): all chord branches)
@@ -992,9 +993,13 @@ printTreeVerboseDiff() ( # $1: stateYaml1, $2: stateYaml2, $3: keyPrefix, $4: se
     fi
 )
 
+printAllTrackerBranches() {
+    git for-each-ref --format='%(refname:short)' refs/heads | awk --assign search='chord/' 'substr($0, 1, length(search)) == search { print }'
+}
+
 printTrackerBranchesForSync() {
     if checkTruthy "$configValue_all"; then
-        git for-each-ref --format='%(refname:short)' refs/heads | awk --assign search='chord/' 'substr($0, 1, length(search)) == search { print }'
+        printAllTrackerBranches
     else
         defaultTrackerBranch="${configValue_trackers_prefix}${configValue_trackers_name}"
         if ! git show-ref --verify --quiet "refs/heads/${defaultTrackerBranch}"; then
@@ -1172,6 +1177,29 @@ if [ "$subcommand" = 'help' ] || [ "$subcommand" = '-h' ]; then
                 'If you use the '\''(`-`)'\'' argument,' \
                 'then the (`<revision>`) parameter will be interpreted as an arbitrary committish' \
                 'It will indicate an error if the specified revision is not a snapshot commit.' \
+            ;
+            exit 0
+            ;;
+        list)
+            printTitle 'git chord list'
+            printSubtitle 'Usage:'
+            printCodeBlock 'git chord list [<name>] [-<n>]'
+            printCodeBlock 'git chord list --all'
+            printSubtitle 'Example:'
+            printCodeBlock 'git chord list -3'
+            printSubtitle 'Description:'
+            printParagraph \
+                'Lists the previously stored snapshots.' \
+                'If you do not specify the (`<name>`) parameter, the default tracker branch will be used.' \
+                'If you specify the (`<n>`) parameter, the output will be restricted to this number of entries.' \
+                'If you use the (`--all`) option, all the tracker branches using the default prefix will be listed,' \
+                'even if the <name> parameter is specified.' \
+            ;
+            printParagraph \
+                'The output is generated by the (`git log`) command using the (`--oneline`) format.' \
+                'If you disable colors (e.g. by using the (`--no-color`) option),' \
+                'then the (`--color=never`) argument will be appended to the (`git log`) command.' \
+                'If you use the (`--markdown`) option, the list will be rendered as simple Markdown list' \
             ;
             exit 0
             ;;
@@ -1919,6 +1947,54 @@ EOF
         else
             printf '%s\n' "$stateYaml"
         fi
+        exit 0
+        ;;
+    list)
+        nameArg="$( getNthLine "$nonOptArgs" 1 )"
+        maxCount=''
+        if [ -z "$nameArg" ]; then
+            targetBranch="${configValue_trackers_prefix}${configValue_trackers_name}"
+        elif checkStartsWith "$nameArg" '-'; then
+            targetBranch="${configValue_trackers_prefix}${configValue_trackers_name}"
+            maxCount="$( printf '%s\n' "$nameArg" | sed -E 's/^\-//' )"
+        else
+            targetBranch="${configValue_trackers_prefix}${nameArg}"
+            stateRevision="$targetBranch"
+            offsetArg="$( getNthLine "$nonOptArgs" 2 )"
+            if checkStartsWith "$offsetArg" '-'; then
+                maxCount="$( printf '%s\n' "$offsetArg" | sed -E 's/^\-//' )"
+            elif [ -n "$offsetArg" ]; then
+                printf '%sERROR: %s: %s%s\n' "$formatError" 'Illegal offset argument' "$offsetArg" "$formatErrorEnd" >&2
+                exit 1
+            fi
+        fi
+        trackerBranches="$targetBranch"
+        if checkTruthy "$configValue_all"; then
+            trackerBranches="$( printAllTrackerBranches )"
+        fi
+        if checkTruthy "$configValue_markdown" || checkTruthy "$configValue_verbose" || checkTruthy "$configValue_all"; then
+            printTitle 'List of existing snapshots'
+        fi
+        
+        # TODO: list commits only that contain state.yaml
+        
+        printf '%s\n' "$trackerBranches" | while IFS='' read -r trackerBranch; do
+            if checkTruthy "$configValue_markdown" || checkTruthy "$configValue_verbose" || checkTruthy "$configValue_all"; then
+                printSubtitle "Snapshots on ${trackerBranch}"
+            fi
+            command="git log ${targetBranch} --first-parent"
+            if [ -n "$maxCount" ]; then
+                command="${command} -n ${maxCount}"
+            fi
+            if checkTruthy "$configValue_markdown"; then
+                command="${command} --oneline --color=never | escapeMarkdown | sed -E 's/^/- /'"
+            elif ! checkTruthy "$configValue_color"; then
+                command="${command} --oneline --color=always"
+            else
+                command="${command} --oneline --color=never"
+            fi
+            eval "$command"
+        done
         exit 0
         ;;
     diff)
